config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"
  get "password_resets/edit"
  get "sessions/new"
  root "static_pages#home"
  get "/users/:id", to: "users#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    resources :relationships, only: [:index]
  end
  resources :acount_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :update, :edit]
  resources :microposts, only: [:create, :destroy]
  resources :relationships
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize object.errors.count, "error" %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %>
    <span class="picture">
      <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
    </span>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to user_relationships_path(@user, relationship: "following") do %>
  <strong id="following" class="stat">
    <%= @user.following.count %>
  </strong>
  Following
  <% end %>
  <%= link_to user_relationships_path(@user, relationship: "followers") do %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Followers
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize current_user.microposts.count, "micropost" %></span>